## 1) Basic List

In [15]:
a = [ 1 , 2 , 3 , 4 , 5 ]
print(a)

[1, 2, 3, 4, 5]


## 2) Basic Numpy

In [16]:
import numpy as np

a = [ 1 , 2 , 3 , 4 , 5 ]
print(a)

b = np.array(a)
print(b)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


## 3) Basic Data Operation

In [17]:
import numpy as np

a = [ 1 , 2 , 3 , 4 , 5 ]
print(a)

a1 = []
for item in a:
    a1.append(item+1)

print(a1)

[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]


In [18]:
b = np.array(a)
print(b)
print(b+1)

[1 2 3 4 5]
[2 3 4 5 6]


## 4) Basic Data Operation 2

In [19]:
import numpy as np

a = [ 1 , 2 , 3 , 4 , 5 ]

b = np.array(a)
d = np.array([ 5 , 4 , 3 , 2 , 1 ])

print(b)
print(d)
print(b+d)

[1 2 3 4 5]
[5 4 3 2 1]
[6 6 6 6 6]


## 5) 2D-Array

In [20]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
c = np.array([a,b])

print(c)
print(c[0]+c[1])
print(c[0]*c[1])

[[1 2 3 4 5]
 [5 4 3 2 1]]
[6 6 6 6 6]
[5 8 9 8 5]


## 6) 2D Array Transpose

In [21]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

c = np.array([a,b])
print(c)
print(c.transpose())

[[1 2 3 4 5]
 [5 4 3 2 1]]
[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]]
